# SpikeReg Default Configuration

# Model architecture
model:
  patch_size: 32
  in_channels: 2  # Fixed + Moving
  base_channels: 16
  encoder_channels: [32, 64, 128]
  decoder_channels: [64, 32, 16]
  
  # Time windows for each level (decreasing)
  encoder_time_windows: [10, 8, 6, 4]
  # decoder_time_windows: [4, 6, 8, 10]
  decoder_time_windows: [4, 4, 4, 4]     # example for 32x32x32 patch, and this is for adjusting the time window of decoder with encoder
  # Input spike encoding
  input_time_window: 10
  
  # Neuron parameters for each level
  encoder_tau_u: [0.9, 0.8, 0.8, 0.7]
  decoder_tau_u: [0.7, 0.8, 0.8, 0.9]
  
  # Skip connection merge strategies
  skip_merge: ['concatenate', 'average', 'concatenate', 'none']
  
  # Displacement scaling
  displacement_scale: 1.0

# Training configuration
training:
  # Pretraining phase
  pretrain: true
  pretrain_epochs: 1
  # pretrain_epochs: 50
  
  # Fine-tuning phase
  # finetune_epochs: 100
  finetune_epochs: 1
  
  # Iterative registration
  num_iterations: 10
  early_stop_threshold: 0.001
  
  # Optimizer
  optimizer:
    type: 'adamw'
    lr: 0.001
    weight_decay: 0.01
  
  # Learning rate scheduler
  scheduler:
    type: 'cosine'
    T_max: 100
    eta_min: 1e-6
  
  # Loss function
  loss:
    similarity_type: 'ncc'
    similarity_weight: 1.0
    regularization_type: 'bending'
    regularization_weight: 0.01
    spike_weight: 0.001
    spike_balance_weight: 0.01
    target_spike_rate: 0.1
  
  # Training settings
  batch_size: 4
  gradient_clip: 1.0
  checkpoint_interval: 10
  log_interval: 10
  
  # Data augmentation
  augmentation:
    rotation_range: 10.0
    scale_range: [0.9, 1.1]
    translation_range: 0.1
    flip_prob: 0.5
    noise_std: 0.01
    intensity_shift: 0.1
    intensity_scale: [0.9, 1.1]

# ANN to SNN conversion
conversion:
  threshold_percentile: 99.0
  calibration_samples: 100

# Inference configuration
inference:
  patch_size: 32
  patch_stride: 16
  batch_size: 8
  smooth_displacement: true

# Data configuration
data:
  # Volume preprocessing
  percentile_clip: [2, 98]
  
  # Patch extraction
  patch_size: 32
  patch_stride: 16
  
  # Validation split
  val_split: 0.2

  # Data paths for L2R Task 3 OASIS dataset
  train_dir: 'data/L2R_2021_Task3_train'
  val_dir: 'data/L2R_2021_Task3_val'
  test_dir: 'data/L2R_2021_Task3_val'

# Neuromorphic deployment
neuromorphic:
  # Quantization
  weight_bits: 8
  threshold_bits: 8
  
  # Core mapping
  cores_per_layer: 4
  max_spikes_per_core: 1000
  
  # Time step
  dt: 1.0  # milliseconds 